// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class Group
{
    public int GroupID { get; set; }

    public string GroupName { get; set; }

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public static implicit operator Group(string v)
    {
        throw new NotImplementedException();
    }
}