// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class Lesson
{
    public int LessonId { get; set; }

    public int GroupId { get; set; }

    public int OfficeId { get; set; }

    public int SubjectId { get; set; }

    public int DayId { get; set; }

    public string LessonsType { get; set; }

    public virtual Day Day { get; set; }

    public virtual Group Group { get; set; }

    public virtual Office Office { get; set; }

    public virtual Subject Subject { get; set; }
}