// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class Office
{
    public int OfficeId { get; set; }

    public int OfficeTypeId { get; set; }

    public int? NumberSeats { get; set; }

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public virtual ICollection<TypeAssign> TypeAssigns { get; set; } = new List<TypeAssign>();
}