// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class Semester
{
    public int SemesterID { get; set; }

    public int SemesterNumber { get; set; }

    public virtual ICollection<Week> Weeks { get; set; } = new List<Week>();
}