// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class Subject
{
    public int SubjectID { get; set; }

    public string SubjectName { get; set; }

    public int HoursPerLecture { get; set; }

    public int HoursPerPractic { get; set; }

    public int HoursPerLaborat { get; set; }

    public int HoursPerConsult { get; set; }

    public int HoursPerExam { get; set; }

    public string Subjectscol { get; set; }

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();
}