// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class TypeAssign
{
    public int AssignmentId { get; set; }

    public int OfficeId { get; set; }

    public int OfficeTypeId { get; set; }

    public virtual Office Office { get; set; }

    public virtual TypeOffice OfficeType { get; set; }
}